// Gives a definition to all the OpenGL functions

#include "opengl.h"

void (GLAPIENTRYP glCullFace)(GLenum mode);
void (GLAPIENTRYP glFrontFace)(GLenum mode);
void (GLAPIENTRYP glHint)(GLenum target, GLenum mode);
void (GLAPIENTRYP glLineWidth)(GLfloat width);
void (GLAPIENTRYP glPointSize)(GLfloat size);
void (GLAPIENTRYP glPolygonMode)(GLenum face, GLenum mode);
void (GLAPIENTRYP glScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glTexParameterf)(GLenum target, GLenum pname, GLfloat param);
void (GLAPIENTRYP glTexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
void (GLAPIENTRYP glTexParameteri)(GLenum target, GLenum pname, GLint param);
void (GLAPIENTRYP glTexParameteriv)(GLenum target, GLenum pname, const GLint *params);
void (GLAPIENTRYP glTexImage1D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glDrawBuffer)(GLenum buf);
void (GLAPIENTRYP glClear)(GLbitfield mask);
void (GLAPIENTRYP glClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (GLAPIENTRYP glClearStencil)(GLint s);
void (GLAPIENTRYP glClearDepth)(GLdouble depth);
void (GLAPIENTRYP glStencilMask)(GLuint mask);
void (GLAPIENTRYP glColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void (GLAPIENTRYP glDepthMask)(GLboolean flag);
void (GLAPIENTRYP glDisable)(GLenum cap);
void (GLAPIENTRYP glEnable)(GLenum cap);
void (GLAPIENTRYP glFinish)(void);
void (GLAPIENTRYP glFlush)(void);
void (GLAPIENTRYP glBlendFunc)(GLenum sfactor, GLenum dfactor);
void (GLAPIENTRYP glLogicOp)(GLenum opcode);
void (GLAPIENTRYP glStencilFunc)(GLenum func, GLint ref, GLuint mask);
void (GLAPIENTRYP glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
void (GLAPIENTRYP glDepthFunc)(GLenum func);
void (GLAPIENTRYP glPixelStoref)(GLenum pname, GLfloat param);
void (GLAPIENTRYP glPixelStorei)(GLenum pname, GLint param);
void (GLAPIENTRYP glReadBuffer)(GLenum src);
void (GLAPIENTRYP glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
void (GLAPIENTRYP glGetBooleanv)(GLenum pname, GLboolean *data);
void (GLAPIENTRYP glGetDoublev)(GLenum pname, GLdouble *data);
GLenum(GLAPIENTRYP glGetError)(void);
void (GLAPIENTRYP glGetFloatv)(GLenum pname, GLfloat *data);
void (GLAPIENTRYP glGetIntegerv)(GLenum pname, GLint *data);
const GLubyte *(GLAPIENTRYP glGetString)(GLenum name);
void (GLAPIENTRYP glGetTexImage)(GLenum target, GLint level, GLenum format, GLenum type, void *pixels);
void (GLAPIENTRYP glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void (GLAPIENTRYP glGetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetTexLevelParameterfv)(GLenum target, GLint level, GLenum pname, GLfloat *params);
void (GLAPIENTRYP glGetTexLevelParameteriv)(GLenum target, GLint level, GLenum pname, GLint *params);
GLboolean(GLAPIENTRYP glIsEnabled)(GLenum cap);
void (GLAPIENTRYP glDepthRange)(GLdouble near, GLdouble far);
void (GLAPIENTRYP glViewport)(GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glDrawArrays)(GLenum mode, GLint first, GLsizei count);
void (GLAPIENTRYP glDrawElements)(GLenum mode, GLsizei count, GLenum type, const void *indices);
void (GLAPIENTRYP glGetPointerv)(GLenum pname, void **params);
void (GLAPIENTRYP glPolygonOffset)(GLfloat factor, GLfloat units);
void (GLAPIENTRYP glCopyTexImage1D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
void (GLAPIENTRYP glCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void (GLAPIENTRYP glCopyTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void (GLAPIENTRYP glCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glBindTexture)(GLenum target, GLuint texture);
void (GLAPIENTRYP glDeleteTextures)(GLsizei n, const GLuint *textures);
void (GLAPIENTRYP glGenTextures)(GLsizei n, GLuint *textures);
GLboolean(GLAPIENTRYP glIsTexture)(GLuint texture);
void (GLAPIENTRYP glDrawRangeElements)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
void (GLAPIENTRYP glTexImage3D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glCopyTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glActiveTexture)(GLenum texture);
void (GLAPIENTRYP glSampleCoverage)(GLfloat value, GLboolean invert);
void (GLAPIENTRYP glCompressedTexImage3D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCompressedTexImage1D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCompressedTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCompressedTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glGetCompressedTexImage)(GLenum target, GLint level, void *img);
void (GLAPIENTRYP glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void (GLAPIENTRYP glMultiDrawArrays)(GLenum mode, const GLint *first, const GLsizei *count, GLsizei drawcount);
void (GLAPIENTRYP glMultiDrawElements)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount);
void (GLAPIENTRYP glPointParameterf)(GLenum pname, GLfloat param);
void (GLAPIENTRYP glPointParameterfv)(GLenum pname, const GLfloat *params);
void (GLAPIENTRYP glPointParameteri)(GLenum pname, GLint param);
void (GLAPIENTRYP glPointParameteriv)(GLenum pname, const GLint *params);
void (GLAPIENTRYP glBlendColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (GLAPIENTRYP glBlendEquation)(GLenum mode);
void (GLAPIENTRYP glGenQueries)(GLsizei n, GLuint *ids);
void (GLAPIENTRYP glDeleteQueries)(GLsizei n, const GLuint *ids);
GLboolean(GLAPIENTRYP glIsQuery)(GLuint id);
void (GLAPIENTRYP glBeginQuery)(GLenum target, GLuint id);
void (GLAPIENTRYP glEndQuery)(GLenum target);
void (GLAPIENTRYP glGetQueryiv)(GLenum target, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetQueryObjectiv)(GLuint id, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetQueryObjectuiv)(GLuint id, GLenum pname, GLuint *params);
void (GLAPIENTRYP glBindBuffer)(GLenum target, GLuint buffer);
void (GLAPIENTRYP glDeleteBuffers)(GLsizei n, const GLuint *buffers);
void (GLAPIENTRYP glGenBuffers)(GLsizei n, GLuint *buffers);
GLboolean(GLAPIENTRYP glIsBuffer)(GLuint buffer);
void (GLAPIENTRYP glBufferData)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
void (GLAPIENTRYP glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
void (GLAPIENTRYP glGetBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, void *data);
void *(GLAPIENTRYP glMapBuffer)(GLenum target, GLenum access);
GLboolean(GLAPIENTRYP glUnmapBuffer)(GLenum target);
void (GLAPIENTRYP glGetBufferParameteriv)(GLenum target, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetBufferPointerv)(GLenum target, GLenum pname, void **params);
void (GLAPIENTRYP glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
void (GLAPIENTRYP glDrawBuffers)(GLsizei n, const GLenum *bufs);
void (GLAPIENTRYP glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void (GLAPIENTRYP glStencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask);
void (GLAPIENTRYP glStencilMaskSeparate)(GLenum face, GLuint mask);
void (GLAPIENTRYP glAttachShader)(GLuint program, GLuint shader);
void (GLAPIENTRYP glBindAttribLocation)(GLuint program, GLuint index, const GLchar *name);
void (GLAPIENTRYP glCompileShader)(GLuint shader);
GLuint(GLAPIENTRYP glCreateProgram)(void);
GLuint(GLAPIENTRYP glCreateShader)(GLenum type);
void (GLAPIENTRYP glDeleteProgram)(GLuint program);
void (GLAPIENTRYP glDeleteShader)(GLuint shader);
void (GLAPIENTRYP glDetachShader)(GLuint program, GLuint shader);
void (GLAPIENTRYP glDisableVertexAttribArray)(GLuint index);
void (GLAPIENTRYP glEnableVertexAttribArray)(GLuint index);
void (GLAPIENTRYP glGetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (GLAPIENTRYP glGetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (GLAPIENTRYP glGetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
GLint(GLAPIENTRYP glGetAttribLocation)(GLuint program, const GLchar *name);
void (GLAPIENTRYP glGetProgramiv)(GLuint program, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (GLAPIENTRYP glGetShaderiv)(GLuint shader, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (GLAPIENTRYP glGetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
GLint(GLAPIENTRYP glGetUniformLocation)(GLuint program, const GLchar *name);
void (GLAPIENTRYP glGetUniformfv)(GLuint program, GLint location, GLfloat *params);
void (GLAPIENTRYP glGetUniformiv)(GLuint program, GLint location, GLint *params);
void (GLAPIENTRYP glGetVertexAttribdv)(GLuint index, GLenum pname, GLdouble *params);
void (GLAPIENTRYP glGetVertexAttribfv)(GLuint index, GLenum pname, GLfloat *params);
void (GLAPIENTRYP glGetVertexAttribiv)(GLuint index, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetVertexAttribPointerv)(GLuint index, GLenum pname, void **pointer);
GLboolean(GLAPIENTRYP glIsProgram)(GLuint program);
GLboolean(GLAPIENTRYP glIsShader)(GLuint shader);
void (GLAPIENTRYP glLinkProgram)(GLuint program);
void (GLAPIENTRYP glShaderSource)(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
void (GLAPIENTRYP glUseProgram)(GLuint program);
void (GLAPIENTRYP glUniform1f)(GLint location, GLfloat v0);
void (GLAPIENTRYP glUniform2f)(GLint location, GLfloat v0, GLfloat v1);
void (GLAPIENTRYP glUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void (GLAPIENTRYP glUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void (GLAPIENTRYP glUniform1i)(GLint location, GLint v0);
void (GLAPIENTRYP glUniform2i)(GLint location, GLint v0, GLint v1);
void (GLAPIENTRYP glUniform3i)(GLint location, GLint v0, GLint v1, GLint v2);
void (GLAPIENTRYP glUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void (GLAPIENTRYP glUniform1fv)(GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glUniform2fv)(GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glUniform3fv)(GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glUniform4fv)(GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glUniform1iv)(GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glUniform2iv)(GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glUniform3iv)(GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glUniform4iv)(GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glValidateProgram)(GLuint program);
void (GLAPIENTRYP glVertexAttrib1d)(GLuint index, GLdouble x);
void (GLAPIENTRYP glVertexAttrib1dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttrib1f)(GLuint index, GLfloat x);
void (GLAPIENTRYP glVertexAttrib1fv)(GLuint index, const GLfloat *v);
void (GLAPIENTRYP glVertexAttrib1s)(GLuint index, GLshort x);
void (GLAPIENTRYP glVertexAttrib1sv)(GLuint index, const GLshort *v);
void (GLAPIENTRYP glVertexAttrib2d)(GLuint index, GLdouble x, GLdouble y);
void (GLAPIENTRYP glVertexAttrib2dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y);
void (GLAPIENTRYP glVertexAttrib2fv)(GLuint index, const GLfloat *v);
void (GLAPIENTRYP glVertexAttrib2s)(GLuint index, GLshort x, GLshort y);
void (GLAPIENTRYP glVertexAttrib2sv)(GLuint index, const GLshort *v);
void (GLAPIENTRYP glVertexAttrib3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
void (GLAPIENTRYP glVertexAttrib3dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
void (GLAPIENTRYP glVertexAttrib3fv)(GLuint index, const GLfloat *v);
void (GLAPIENTRYP glVertexAttrib3s)(GLuint index, GLshort x, GLshort y, GLshort z);
void (GLAPIENTRYP glVertexAttrib3sv)(GLuint index, const GLshort *v);
void (GLAPIENTRYP glVertexAttrib4Nbv)(GLuint index, const GLbyte *v);
void (GLAPIENTRYP glVertexAttrib4Niv)(GLuint index, const GLint *v);
void (GLAPIENTRYP glVertexAttrib4Nsv)(GLuint index, const GLshort *v);
void (GLAPIENTRYP glVertexAttrib4Nub)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
void (GLAPIENTRYP glVertexAttrib4Nubv)(GLuint index, const GLubyte *v);
void (GLAPIENTRYP glVertexAttrib4Nuiv)(GLuint index, const GLuint *v);
void (GLAPIENTRYP glVertexAttrib4Nusv)(GLuint index, const GLushort *v);
void (GLAPIENTRYP glVertexAttrib4bv)(GLuint index, const GLbyte *v);
void (GLAPIENTRYP glVertexAttrib4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void (GLAPIENTRYP glVertexAttrib4dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void (GLAPIENTRYP glVertexAttrib4fv)(GLuint index, const GLfloat *v);
void (GLAPIENTRYP glVertexAttrib4iv)(GLuint index, const GLint *v);
void (GLAPIENTRYP glVertexAttrib4s)(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
void (GLAPIENTRYP glVertexAttrib4sv)(GLuint index, const GLshort *v);
void (GLAPIENTRYP glVertexAttrib4ubv)(GLuint index, const GLubyte *v);
void (GLAPIENTRYP glVertexAttrib4uiv)(GLuint index, const GLuint *v);
void (GLAPIENTRYP glVertexAttrib4usv)(GLuint index, const GLushort *v);
void (GLAPIENTRYP glVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
void (GLAPIENTRYP glUniformMatrix2x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glUniformMatrix3x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glUniformMatrix2x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glUniformMatrix4x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glUniformMatrix3x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glUniformMatrix4x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glColorMaski)(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
void (GLAPIENTRYP glGetBooleani_v)(GLenum target, GLuint index, GLboolean *data);
void (GLAPIENTRYP glGetIntegeri_v)(GLenum target, GLuint index, GLint *data);
void (GLAPIENTRYP glEnablei)(GLenum target, GLuint index);
void (GLAPIENTRYP glDisablei)(GLenum target, GLuint index);
GLboolean(GLAPIENTRYP glIsEnabledi)(GLenum target, GLuint index);
void (GLAPIENTRYP glBeginTransformFeedback)(GLenum primitiveMode);
void (GLAPIENTRYP glEndTransformFeedback)(void);
void (GLAPIENTRYP glBindBufferRange)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (GLAPIENTRYP glBindBufferBase)(GLenum target, GLuint index, GLuint buffer);
void (GLAPIENTRYP glTransformFeedbackVaryings)(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode);
void (GLAPIENTRYP glGetTransformFeedbackVarying)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
void (GLAPIENTRYP glClampColor)(GLenum target, GLenum clamp);
void (GLAPIENTRYP glBeginConditionalRender)(GLuint id, GLenum mode);
void (GLAPIENTRYP glEndConditionalRender)(void);
void (GLAPIENTRYP glVertexAttribIPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
void (GLAPIENTRYP glGetVertexAttribIiv)(GLuint index, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetVertexAttribIuiv)(GLuint index, GLenum pname, GLuint *params);
void (GLAPIENTRYP glVertexAttribI1i)(GLuint index, GLint x);
void (GLAPIENTRYP glVertexAttribI2i)(GLuint index, GLint x, GLint y);
void (GLAPIENTRYP glVertexAttribI3i)(GLuint index, GLint x, GLint y, GLint z);
void (GLAPIENTRYP glVertexAttribI4i)(GLuint index, GLint x, GLint y, GLint z, GLint w);
void (GLAPIENTRYP glVertexAttribI1ui)(GLuint index, GLuint x);
void (GLAPIENTRYP glVertexAttribI2ui)(GLuint index, GLuint x, GLuint y);
void (GLAPIENTRYP glVertexAttribI3ui)(GLuint index, GLuint x, GLuint y, GLuint z);
void (GLAPIENTRYP glVertexAttribI4ui)(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
void (GLAPIENTRYP glVertexAttribI1iv)(GLuint index, const GLint *v);
void (GLAPIENTRYP glVertexAttribI2iv)(GLuint index, const GLint *v);
void (GLAPIENTRYP glVertexAttribI3iv)(GLuint index, const GLint *v);
void (GLAPIENTRYP glVertexAttribI4iv)(GLuint index, const GLint *v);
void (GLAPIENTRYP glVertexAttribI1uiv)(GLuint index, const GLuint *v);
void (GLAPIENTRYP glVertexAttribI2uiv)(GLuint index, const GLuint *v);
void (GLAPIENTRYP glVertexAttribI3uiv)(GLuint index, const GLuint *v);
void (GLAPIENTRYP glVertexAttribI4uiv)(GLuint index, const GLuint *v);
void (GLAPIENTRYP glVertexAttribI4bv)(GLuint index, const GLbyte *v);
void (GLAPIENTRYP glVertexAttribI4sv)(GLuint index, const GLshort *v);
void (GLAPIENTRYP glVertexAttribI4ubv)(GLuint index, const GLubyte *v);
void (GLAPIENTRYP glVertexAttribI4usv)(GLuint index, const GLushort *v);
void (GLAPIENTRYP glGetUniformuiv)(GLuint program, GLint location, GLuint *params);
void (GLAPIENTRYP glBindFragDataLocation)(GLuint program, GLuint color, const GLchar *name);
GLint(GLAPIENTRYP glGetFragDataLocation)(GLuint program, const GLchar *name);
void (GLAPIENTRYP glUniform1ui)(GLint location, GLuint v0);
void (GLAPIENTRYP glUniform2ui)(GLint location, GLuint v0, GLuint v1);
void (GLAPIENTRYP glUniform3ui)(GLint location, GLuint v0, GLuint v1, GLuint v2);
void (GLAPIENTRYP glUniform4ui)(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void (GLAPIENTRYP glUniform1uiv)(GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glUniform2uiv)(GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glUniform3uiv)(GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glUniform4uiv)(GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glTexParameterIiv)(GLenum target, GLenum pname, const GLint *params);
void (GLAPIENTRYP glTexParameterIuiv)(GLenum target, GLenum pname, const GLuint *params);
void (GLAPIENTRYP glGetTexParameterIiv)(GLenum target, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetTexParameterIuiv)(GLenum target, GLenum pname, GLuint *params);
void (GLAPIENTRYP glClearBufferiv)(GLenum buffer, GLint drawbuffer, const GLint *value);
void (GLAPIENTRYP glClearBufferuiv)(GLenum buffer, GLint drawbuffer, const GLuint *value);
void (GLAPIENTRYP glClearBufferfv)(GLenum buffer, GLint drawbuffer, const GLfloat *value);
void (GLAPIENTRYP glClearBufferfi)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
const GLubyte *(GLAPIENTRYP glGetStringi)(GLenum name, GLuint index);
GLboolean(GLAPIENTRYP glIsRenderbuffer)(GLuint renderbuffer);
void (GLAPIENTRYP glBindRenderbuffer)(GLenum target, GLuint renderbuffer);
void (GLAPIENTRYP glDeleteRenderbuffers)(GLsizei n, const GLuint *renderbuffers);
void (GLAPIENTRYP glGenRenderbuffers)(GLsizei n, GLuint *renderbuffers);
void (GLAPIENTRYP glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void (GLAPIENTRYP glGetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint *params);
GLboolean(GLAPIENTRYP glIsFramebuffer)(GLuint framebuffer);
void (GLAPIENTRYP glBindFramebuffer)(GLenum target, GLuint framebuffer);
void (GLAPIENTRYP glDeleteFramebuffers)(GLsizei n, const GLuint *framebuffers);
void (GLAPIENTRYP glGenFramebuffers)(GLsizei n, GLuint *framebuffers);
GLenum(GLAPIENTRYP glCheckFramebufferStatus)(GLenum target);
void (GLAPIENTRYP glFramebufferTexture1D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void (GLAPIENTRYP glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void (GLAPIENTRYP glFramebufferTexture3D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
void (GLAPIENTRYP glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void (GLAPIENTRYP glGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint *params);
void (GLAPIENTRYP glGenerateMipmap)(GLenum target);
void (GLAPIENTRYP glBlitFramebuffer)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
void (GLAPIENTRYP glRenderbufferStorageMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void (GLAPIENTRYP glFramebufferTextureLayer)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
void *(GLAPIENTRYP glMapBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
void (GLAPIENTRYP glFlushMappedBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length);
void (GLAPIENTRYP glBindVertexArray)(GLuint array);
void (GLAPIENTRYP glDeleteVertexArrays)(GLsizei n, const GLuint *arrays);
void (GLAPIENTRYP glGenVertexArrays)(GLsizei n, GLuint *arrays);
GLboolean(GLAPIENTRYP glIsVertexArray)(GLuint array);
void (GLAPIENTRYP glDrawArraysInstanced)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
void (GLAPIENTRYP glDrawElementsInstanced)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
void (GLAPIENTRYP glTexBuffer)(GLenum target, GLenum internalformat, GLuint buffer);
void (GLAPIENTRYP glPrimitiveRestartIndex)(GLuint index);
void (GLAPIENTRYP glCopyBufferSubData)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void (GLAPIENTRYP glGetUniformIndices)(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices);
void (GLAPIENTRYP glGetActiveUniformsiv)(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetActiveUniformName)(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName);
GLuint(GLAPIENTRYP glGetUniformBlockIndex)(GLuint program, const GLchar *uniformBlockName);
void (GLAPIENTRYP glGetActiveUniformBlockiv)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetActiveUniformBlockName)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
void (GLAPIENTRYP glUniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
void (GLAPIENTRYP glDrawElementsBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
void (GLAPIENTRYP glDrawRangeElementsBaseVertex)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
void (GLAPIENTRYP glDrawElementsInstancedBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
void (GLAPIENTRYP glMultiDrawElementsBaseVertex)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount, const GLint *basevertex);
void (GLAPIENTRYP glProvokingVertex)(GLenum mode);
GLsync(GLAPIENTRYP glFenceSync)(GLenum condition, GLbitfield flags);
GLboolean(GLAPIENTRYP glIsSync)(GLsync sync);
void (GLAPIENTRYP glDeleteSync)(GLsync sync);
GLenum(GLAPIENTRYP glClientWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
void (GLAPIENTRYP glWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
void (GLAPIENTRYP glGetInteger64v)(GLenum pname, GLint64 *data);
void (GLAPIENTRYP glGetSynciv)(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
void (GLAPIENTRYP glGetInteger64i_v)(GLenum target, GLuint index, GLint64 *data);
void (GLAPIENTRYP glGetBufferParameteri64v)(GLenum target, GLenum pname, GLint64 *params);
void (GLAPIENTRYP glFramebufferTexture)(GLenum target, GLenum attachment, GLuint texture, GLint level);
void (GLAPIENTRYP glTexImage2DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void (GLAPIENTRYP glTexImage3DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
void (GLAPIENTRYP glGetMultisamplefv)(GLenum pname, GLuint index, GLfloat *val);
void (GLAPIENTRYP glSampleMaski)(GLuint maskNumber, GLbitfield mask);
void (GLAPIENTRYP glBindFragDataLocationIndexed)(GLuint program, GLuint colorNumber, GLuint index, const GLchar *name);
GLint(GLAPIENTRYP glGetFragDataIndex)(GLuint program, const GLchar *name);
void (GLAPIENTRYP glGenSamplers)(GLsizei count, GLuint *samplers);
void (GLAPIENTRYP glDeleteSamplers)(GLsizei count, const GLuint *samplers);
GLboolean(GLAPIENTRYP glIsSampler)(GLuint sampler);
void (GLAPIENTRYP glBindSampler)(GLuint unit, GLuint sampler);
void (GLAPIENTRYP glSamplerParameteri)(GLuint sampler, GLenum pname, GLint param);
void (GLAPIENTRYP glSamplerParameteriv)(GLuint sampler, GLenum pname, const GLint *param);
void (GLAPIENTRYP glSamplerParameterf)(GLuint sampler, GLenum pname, GLfloat param);
void (GLAPIENTRYP glSamplerParameterfv)(GLuint sampler, GLenum pname, const GLfloat *param);
void (GLAPIENTRYP glSamplerParameterIiv)(GLuint sampler, GLenum pname, const GLint *param);
void (GLAPIENTRYP glSamplerParameterIuiv)(GLuint sampler, GLenum pname, const GLuint *param);
void (GLAPIENTRYP glGetSamplerParameteriv)(GLuint sampler, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetSamplerParameterIiv)(GLuint sampler, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetSamplerParameterfv)(GLuint sampler, GLenum pname, GLfloat *params);
void (GLAPIENTRYP glGetSamplerParameterIuiv)(GLuint sampler, GLenum pname, GLuint *params);
void (GLAPIENTRYP glQueryCounter)(GLuint id, GLenum target);
void (GLAPIENTRYP glGetQueryObjecti64v)(GLuint id, GLenum pname, GLint64 *params);
void (GLAPIENTRYP glGetQueryObjectui64v)(GLuint id, GLenum pname, GLuint64 *params);
void (GLAPIENTRYP glVertexAttribDivisor)(GLuint index, GLuint divisor);
void (GLAPIENTRYP glVertexAttribP1ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (GLAPIENTRYP glVertexAttribP1uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (GLAPIENTRYP glVertexAttribP2ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (GLAPIENTRYP glVertexAttribP2uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (GLAPIENTRYP glVertexAttribP3ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (GLAPIENTRYP glVertexAttribP3uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (GLAPIENTRYP glVertexAttribP4ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
void (GLAPIENTRYP glVertexAttribP4uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
void (GLAPIENTRYP glMinSampleShading)(GLfloat value);
void (GLAPIENTRYP glBlendEquationi)(GLuint buf, GLenum mode);
void (GLAPIENTRYP glBlendEquationSeparatei)(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
void (GLAPIENTRYP glBlendFunci)(GLuint buf, GLenum src, GLenum dst);
void (GLAPIENTRYP glBlendFuncSeparatei)(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void (GLAPIENTRYP glDrawArraysIndirect)(GLenum mode, const void *indirect);
void (GLAPIENTRYP glDrawElementsIndirect)(GLenum mode, GLenum type, const void *indirect);
void (GLAPIENTRYP glUniform1d)(GLint location, GLdouble x);
void (GLAPIENTRYP glUniform2d)(GLint location, GLdouble x, GLdouble y);
void (GLAPIENTRYP glUniform3d)(GLint location, GLdouble x, GLdouble y, GLdouble z);
void (GLAPIENTRYP glUniform4d)(GLint location, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void (GLAPIENTRYP glUniform1dv)(GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glUniform2dv)(GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glUniform3dv)(GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glUniform4dv)(GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix2x3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix2x4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix3x2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix3x4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix4x2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glUniformMatrix4x3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glGetUniformdv)(GLuint program, GLint location, GLdouble *params);
GLint(GLAPIENTRYP glGetSubroutineUniformLocation)(GLuint program, GLenum shadertype, const GLchar *name);
GLuint(GLAPIENTRYP glGetSubroutineIndex)(GLuint program, GLenum shadertype, const GLchar *name);
void (GLAPIENTRYP glGetActiveSubroutineUniformiv)(GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint *values);
void (GLAPIENTRYP glGetActiveSubroutineUniformName)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name);
void (GLAPIENTRYP glGetActiveSubroutineName)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name);
void (GLAPIENTRYP glUniformSubroutinesuiv)(GLenum shadertype, GLsizei count, const GLuint *indices);
void (GLAPIENTRYP glGetUniformSubroutineuiv)(GLenum shadertype, GLint location, GLuint *params);
void (GLAPIENTRYP glGetProgramStageiv)(GLuint program, GLenum shadertype, GLenum pname, GLint *values);
void (GLAPIENTRYP glPatchParameteri)(GLenum pname, GLint value);
void (GLAPIENTRYP glPatchParameterfv)(GLenum pname, const GLfloat *values);
void (GLAPIENTRYP glBindTransformFeedback)(GLenum target, GLuint id);
void (GLAPIENTRYP glDeleteTransformFeedbacks)(GLsizei n, const GLuint *ids);
void (GLAPIENTRYP glGenTransformFeedbacks)(GLsizei n, GLuint *ids);
GLboolean(GLAPIENTRYP glIsTransformFeedback)(GLuint id);
void (GLAPIENTRYP glPauseTransformFeedback)(void);
void (GLAPIENTRYP glResumeTransformFeedback)(void);
void (GLAPIENTRYP glDrawTransformFeedback)(GLenum mode, GLuint id);
void (GLAPIENTRYP glDrawTransformFeedbackStream)(GLenum mode, GLuint id, GLuint stream);
void (GLAPIENTRYP glBeginQueryIndexed)(GLenum target, GLuint index, GLuint id);
void (GLAPIENTRYP glEndQueryIndexed)(GLenum target, GLuint index);
void (GLAPIENTRYP glGetQueryIndexediv)(GLenum target, GLuint index, GLenum pname, GLint *params);
void (GLAPIENTRYP glReleaseShaderCompiler)(void);
void (GLAPIENTRYP glShaderBinary)(GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length);
void (GLAPIENTRYP glGetShaderPrecisionFormat)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
void (GLAPIENTRYP glDepthRangef)(GLfloat n, GLfloat f);
void (GLAPIENTRYP glClearDepthf)(GLfloat d);
void (GLAPIENTRYP glGetProgramBinary)(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
void (GLAPIENTRYP glProgramBinary)(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
void (GLAPIENTRYP glProgramParameteri)(GLuint program, GLenum pname, GLint value);
void (GLAPIENTRYP glUseProgramStages)(GLuint pipeline, GLbitfield stages, GLuint program);
void (GLAPIENTRYP glActiveShaderProgram)(GLuint pipeline, GLuint program);
GLuint(GLAPIENTRYP glCreateShaderProgramv)(GLenum type, GLsizei count, const GLchar *const*strings);
void (GLAPIENTRYP glBindProgramPipeline)(GLuint pipeline);
void (GLAPIENTRYP glDeleteProgramPipelines)(GLsizei n, const GLuint *pipelines);
void (GLAPIENTRYP glGenProgramPipelines)(GLsizei n, GLuint *pipelines);
GLboolean(GLAPIENTRYP glIsProgramPipeline)(GLuint pipeline);
void (GLAPIENTRYP glGetProgramPipelineiv)(GLuint pipeline, GLenum pname, GLint *params);
void (GLAPIENTRYP glProgramUniform1i)(GLuint program, GLint location, GLint v0);
void (GLAPIENTRYP glProgramUniform1iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glProgramUniform1f)(GLuint program, GLint location, GLfloat v0);
void (GLAPIENTRYP glProgramUniform1fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glProgramUniform1d)(GLuint program, GLint location, GLdouble v0);
void (GLAPIENTRYP glProgramUniform1dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glProgramUniform1ui)(GLuint program, GLint location, GLuint v0);
void (GLAPIENTRYP glProgramUniform1uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glProgramUniform2i)(GLuint program, GLint location, GLint v0, GLint v1);
void (GLAPIENTRYP glProgramUniform2iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glProgramUniform2f)(GLuint program, GLint location, GLfloat v0, GLfloat v1);
void (GLAPIENTRYP glProgramUniform2fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glProgramUniform2d)(GLuint program, GLint location, GLdouble v0, GLdouble v1);
void (GLAPIENTRYP glProgramUniform2dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glProgramUniform2ui)(GLuint program, GLint location, GLuint v0, GLuint v1);
void (GLAPIENTRYP glProgramUniform2uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glProgramUniform3i)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
void (GLAPIENTRYP glProgramUniform3iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glProgramUniform3f)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void (GLAPIENTRYP glProgramUniform3fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glProgramUniform3d)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2);
void (GLAPIENTRYP glProgramUniform3dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glProgramUniform3ui)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
void (GLAPIENTRYP glProgramUniform3uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glProgramUniform4i)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void (GLAPIENTRYP glProgramUniform4iv)(GLuint program, GLint location, GLsizei count, const GLint *value);
void (GLAPIENTRYP glProgramUniform4f)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void (GLAPIENTRYP glProgramUniform4fv)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
void (GLAPIENTRYP glProgramUniform4d)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
void (GLAPIENTRYP glProgramUniform4dv)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
void (GLAPIENTRYP glProgramUniform4ui)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void (GLAPIENTRYP glProgramUniform4uiv)(GLuint program, GLint location, GLsizei count, const GLuint *value);
void (GLAPIENTRYP glProgramUniformMatrix2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix2x3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix3x2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix2x4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix4x2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix3x4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix4x3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GLAPIENTRYP glProgramUniformMatrix2x3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix3x2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix2x4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix4x2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix3x4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glProgramUniformMatrix4x3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
void (GLAPIENTRYP glValidateProgramPipeline)(GLuint pipeline);
void (GLAPIENTRYP glGetProgramPipelineInfoLog)(GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (GLAPIENTRYP glVertexAttribL1d)(GLuint index, GLdouble x);
void (GLAPIENTRYP glVertexAttribL2d)(GLuint index, GLdouble x, GLdouble y);
void (GLAPIENTRYP glVertexAttribL3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
void (GLAPIENTRYP glVertexAttribL4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void (GLAPIENTRYP glVertexAttribL1dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttribL2dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttribL3dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttribL4dv)(GLuint index, const GLdouble *v);
void (GLAPIENTRYP glVertexAttribLPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
void (GLAPIENTRYP glGetVertexAttribLdv)(GLuint index, GLenum pname, GLdouble *params);
void (GLAPIENTRYP glViewportArrayv)(GLuint first, GLsizei count, const GLfloat *v);
void (GLAPIENTRYP glViewportIndexedf)(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
void (GLAPIENTRYP glViewportIndexedfv)(GLuint index, const GLfloat *v);
void (GLAPIENTRYP glScissorArrayv)(GLuint first, GLsizei count, const GLint *v);
void (GLAPIENTRYP glScissorIndexed)(GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height);
void (GLAPIENTRYP glScissorIndexedv)(GLuint index, const GLint *v);
void (GLAPIENTRYP glDepthRangeArrayv)(GLuint first, GLsizei count, const GLdouble *v);
void (GLAPIENTRYP glDepthRangeIndexed)(GLuint index, GLdouble n, GLdouble f);
void (GLAPIENTRYP glGetFloati_v)(GLenum target, GLuint index, GLfloat *data);
void (GLAPIENTRYP glGetDoublei_v)(GLenum target, GLuint index, GLdouble *data);
void (GLAPIENTRYP glDrawArraysInstancedBaseInstance)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
void (GLAPIENTRYP glDrawElementsInstancedBaseInstance)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLuint baseinstance);
void (GLAPIENTRYP glDrawElementsInstancedBaseVertexBaseInstance)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
void (GLAPIENTRYP glGetInternalformativ)(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params);
void (GLAPIENTRYP glGetActiveAtomicCounterBufferiv)(GLuint program, GLuint bufferIndex, GLenum pname, GLint *params);
void (GLAPIENTRYP glBindImageTexture)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
void (GLAPIENTRYP glMemoryBarrier)(GLbitfield barriers);
void (GLAPIENTRYP glTexStorage1D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
void (GLAPIENTRYP glTexStorage2D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void (GLAPIENTRYP glTexStorage3D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
void (GLAPIENTRYP glDrawTransformFeedbackInstanced)(GLenum mode, GLuint id, GLsizei instancecount);
void (GLAPIENTRYP glDrawTransformFeedbackStreamInstanced)(GLenum mode, GLuint id, GLuint stream, GLsizei instancecount);
void (GLAPIENTRYP glClearBufferData)(GLenum target, GLenum internalformat, GLenum format, GLenum type, const void *data);
void (GLAPIENTRYP glClearBufferSubData)(GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
void (GLAPIENTRYP glDispatchCompute)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
void (GLAPIENTRYP glDispatchComputeIndirect)(GLintptr indirect);
void (GLAPIENTRYP glCopyImageSubData)(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
void (GLAPIENTRYP glFramebufferParameteri)(GLenum target, GLenum pname, GLint param);
void (GLAPIENTRYP glGetFramebufferParameteriv)(GLenum target, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetInternalformati64v)(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 *params);
void (GLAPIENTRYP glInvalidateTexSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth);
void (GLAPIENTRYP glInvalidateTexImage)(GLuint texture, GLint level);
void (GLAPIENTRYP glInvalidateBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr length);
void (GLAPIENTRYP glInvalidateBufferData)(GLuint buffer);
void (GLAPIENTRYP glInvalidateFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum *attachments);
void (GLAPIENTRYP glInvalidateSubFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glMultiDrawArraysIndirect)(GLenum mode, const void *indirect, GLsizei drawcount, GLsizei stride);
void (GLAPIENTRYP glMultiDrawElementsIndirect)(GLenum mode, GLenum type, const void *indirect, GLsizei drawcount, GLsizei stride);
void (GLAPIENTRYP glGetProgramInterfaceiv)(GLuint program, GLenum programInterface, GLenum pname, GLint *params);
GLuint(GLAPIENTRYP glGetProgramResourceIndex)(GLuint program, GLenum programInterface, const GLchar *name);
void (GLAPIENTRYP glGetProgramResourceName)(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
void (GLAPIENTRYP glGetProgramResourceiv)(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
GLint(GLAPIENTRYP glGetProgramResourceLocation)(GLuint program, GLenum programInterface, const GLchar *name);
GLint(GLAPIENTRYP glGetProgramResourceLocationIndex)(GLuint program, GLenum programInterface, const GLchar *name);
void (GLAPIENTRYP glShaderStorageBlockBinding)(GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
void (GLAPIENTRYP glTexBufferRange)(GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (GLAPIENTRYP glTexStorage2DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void (GLAPIENTRYP glTexStorage3DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
void (GLAPIENTRYP glTextureView)(GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers);
void (GLAPIENTRYP glBindVertexBuffer)(GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
void (GLAPIENTRYP glVertexAttribFormat)(GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
void (GLAPIENTRYP glVertexAttribIFormat)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (GLAPIENTRYP glVertexAttribLFormat)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (GLAPIENTRYP glVertexAttribBinding)(GLuint attribindex, GLuint bindingindex);
void (GLAPIENTRYP glVertexBindingDivisor)(GLuint bindingindex, GLuint divisor);
void (GLAPIENTRYP glDebugMessageControl)(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
void (GLAPIENTRYP glDebugMessageInsert)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
void (GLAPIENTRYP glDebugMessageCallback)(GLDEBUGPROC callback, const void *userParam);
GLuint(GLAPIENTRYP glGetDebugMessageLog)(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog);
void (GLAPIENTRYP glPushDebugGroup)(GLenum source, GLuint id, GLsizei length, const GLchar *message);
void (GLAPIENTRYP glPopDebugGroup)(void);
void (GLAPIENTRYP glObjectLabel)(GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
void (GLAPIENTRYP glGetObjectLabel)(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
void (GLAPIENTRYP glObjectPtrLabel)(const void *ptr, GLsizei length, const GLchar *label);
void (GLAPIENTRYP glGetObjectPtrLabel)(const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);
void (GLAPIENTRYP glBufferStorage)(GLenum target, GLsizeiptr size, const void *data, GLbitfield flags);
void (GLAPIENTRYP glClearTexImage)(GLuint texture, GLint level, GLenum format, GLenum type, const void *data);
void (GLAPIENTRYP glClearTexSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data);
void (GLAPIENTRYP glBindBuffersBase)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers);
void (GLAPIENTRYP glBindBuffersRange)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes);
void (GLAPIENTRYP glBindTextures)(GLuint first, GLsizei count, const GLuint *textures);
void (GLAPIENTRYP glBindSamplers)(GLuint first, GLsizei count, const GLuint *samplers);
void (GLAPIENTRYP glBindImageTextures)(GLuint first, GLsizei count, const GLuint *textures);
void (GLAPIENTRYP glBindVertexBuffers)(GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
void (GLAPIENTRYP glClipControl)(GLenum origin, GLenum depth);
void (GLAPIENTRYP glCreateTransformFeedbacks)(GLsizei n, GLuint *ids);
void (GLAPIENTRYP glTransformFeedbackBufferBase)(GLuint xfb, GLuint index, GLuint buffer);
void (GLAPIENTRYP glTransformFeedbackBufferRange)(GLuint xfb, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (GLAPIENTRYP glGetTransformFeedbackiv)(GLuint xfb, GLenum pname, GLint *param);
void (GLAPIENTRYP glGetTransformFeedbacki_v)(GLuint xfb, GLenum pname, GLuint index, GLint *param);
void (GLAPIENTRYP glGetTransformFeedbacki64_v)(GLuint xfb, GLenum pname, GLuint index, GLint64 *param);
void (GLAPIENTRYP glCreateBuffers)(GLsizei n, GLuint *buffers);
void (GLAPIENTRYP glNamedBufferStorage)(GLuint buffer, GLsizeiptr size, const void *data, GLbitfield flags);
void (GLAPIENTRYP glNamedBufferData)(GLuint buffer, GLsizeiptr size, const void *data, GLenum usage);
void (GLAPIENTRYP glNamedBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr size, const void *data);
void (GLAPIENTRYP glCopyNamedBufferSubData)(GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void (GLAPIENTRYP glClearNamedBufferData)(GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const void *data);
void (GLAPIENTRYP glClearNamedBufferSubData)(GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
void *(GLAPIENTRYP glMapNamedBuffer)(GLuint buffer, GLenum access);
void *(GLAPIENTRYP glMapNamedBufferRange)(GLuint buffer, GLintptr offset, GLsizeiptr length, GLbitfield access);
GLboolean(GLAPIENTRYP glUnmapNamedBuffer)(GLuint buffer);
void (GLAPIENTRYP glFlushMappedNamedBufferRange)(GLuint buffer, GLintptr offset, GLsizeiptr length);
void (GLAPIENTRYP glGetNamedBufferParameteriv)(GLuint buffer, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetNamedBufferParameteri64v)(GLuint buffer, GLenum pname, GLint64 *params);
void (GLAPIENTRYP glGetNamedBufferPointerv)(GLuint buffer, GLenum pname, void **params);
void (GLAPIENTRYP glGetNamedBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr size, void *data);
void (GLAPIENTRYP glCreateFramebuffers)(GLsizei n, GLuint *framebuffers);
void (GLAPIENTRYP glNamedFramebufferRenderbuffer)(GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void (GLAPIENTRYP glNamedFramebufferParameteri)(GLuint framebuffer, GLenum pname, GLint param);
void (GLAPIENTRYP glNamedFramebufferTexture)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level);
void (GLAPIENTRYP glNamedFramebufferTextureLayer)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer);
void (GLAPIENTRYP glNamedFramebufferDrawBuffer)(GLuint framebuffer, GLenum buf);
void (GLAPIENTRYP glNamedFramebufferDrawBuffers)(GLuint framebuffer, GLsizei n, const GLenum *bufs);
void (GLAPIENTRYP glNamedFramebufferReadBuffer)(GLuint framebuffer, GLenum src);
void (GLAPIENTRYP glInvalidateNamedFramebufferData)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments);
void (GLAPIENTRYP glInvalidateNamedFramebufferSubData)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glClearNamedFramebufferiv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLint *value);
void (GLAPIENTRYP glClearNamedFramebufferuiv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLuint *value);
void (GLAPIENTRYP glClearNamedFramebufferfv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat *value);
void (GLAPIENTRYP glClearNamedFramebufferfi)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
void (GLAPIENTRYP glBlitNamedFramebuffer)(GLuint readFramebuffer, GLuint drawFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
GLenum(GLAPIENTRYP glCheckNamedFramebufferStatus)(GLuint framebuffer, GLenum target);
void (GLAPIENTRYP glGetNamedFramebufferParameteriv)(GLuint framebuffer, GLenum pname, GLint *param);
void (GLAPIENTRYP glGetNamedFramebufferAttachmentParameteriv)(GLuint framebuffer, GLenum attachment, GLenum pname, GLint *params);
void (GLAPIENTRYP glCreateRenderbuffers)(GLsizei n, GLuint *renderbuffers);
void (GLAPIENTRYP glNamedRenderbufferStorage)(GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height);
void (GLAPIENTRYP glNamedRenderbufferStorageMultisample)(GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void (GLAPIENTRYP glGetNamedRenderbufferParameteriv)(GLuint renderbuffer, GLenum pname, GLint *params);
void (GLAPIENTRYP glCreateTextures)(GLenum target, GLsizei n, GLuint *textures);
void (GLAPIENTRYP glTextureBuffer)(GLuint texture, GLenum internalformat, GLuint buffer);
void (GLAPIENTRYP glTextureBufferRange)(GLuint texture, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (GLAPIENTRYP glTextureStorage1D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width);
void (GLAPIENTRYP glTextureStorage2D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void (GLAPIENTRYP glTextureStorage3D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
void (GLAPIENTRYP glTextureStorage2DMultisample)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void (GLAPIENTRYP glTextureStorage3DMultisample)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
void (GLAPIENTRYP glTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
void (GLAPIENTRYP glCompressedTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCompressedTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCompressedTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
void (GLAPIENTRYP glCopyTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void (GLAPIENTRYP glCopyTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glCopyTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (GLAPIENTRYP glTextureParameterf)(GLuint texture, GLenum pname, GLfloat param);
void (GLAPIENTRYP glTextureParameterfv)(GLuint texture, GLenum pname, const GLfloat *param);
void (GLAPIENTRYP glTextureParameteri)(GLuint texture, GLenum pname, GLint param);
void (GLAPIENTRYP glTextureParameterIiv)(GLuint texture, GLenum pname, const GLint *params);
void (GLAPIENTRYP glTextureParameterIuiv)(GLuint texture, GLenum pname, const GLuint *params);
void (GLAPIENTRYP glTextureParameteriv)(GLuint texture, GLenum pname, const GLint *param);
void (GLAPIENTRYP glGenerateTextureMipmap)(GLuint texture);
void (GLAPIENTRYP glBindTextureUnit)(GLuint unit, GLuint texture);
void (GLAPIENTRYP glGetTextureImage)(GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
void (GLAPIENTRYP glGetCompressedTextureImage)(GLuint texture, GLint level, GLsizei bufSize, void *pixels);
void (GLAPIENTRYP glGetTextureLevelParameterfv)(GLuint texture, GLint level, GLenum pname, GLfloat *params);
void (GLAPIENTRYP glGetTextureLevelParameteriv)(GLuint texture, GLint level, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetTextureParameterfv)(GLuint texture, GLenum pname, GLfloat *params);
void (GLAPIENTRYP glGetTextureParameterIiv)(GLuint texture, GLenum pname, GLint *params);
void (GLAPIENTRYP glGetTextureParameterIuiv)(GLuint texture, GLenum pname, GLuint *params);
void (GLAPIENTRYP glGetTextureParameteriv)(GLuint texture, GLenum pname, GLint *params);
void (GLAPIENTRYP glCreateVertexArrays)(GLsizei n, GLuint *arrays);
void (GLAPIENTRYP glDisableVertexArrayAttrib)(GLuint vaobj, GLuint index);
void (GLAPIENTRYP glEnableVertexArrayAttrib)(GLuint vaobj, GLuint index);
void (GLAPIENTRYP glVertexArrayElementBuffer)(GLuint vaobj, GLuint buffer);
void (GLAPIENTRYP glVertexArrayVertexBuffer)(GLuint vaobj, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
void (GLAPIENTRYP glVertexArrayVertexBuffers)(GLuint vaobj, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
void (GLAPIENTRYP glVertexArrayAttribBinding)(GLuint vaobj, GLuint attribindex, GLuint bindingindex);
void (GLAPIENTRYP glVertexArrayAttribFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
void (GLAPIENTRYP glVertexArrayAttribIFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (GLAPIENTRYP glVertexArrayAttribLFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void (GLAPIENTRYP glVertexArrayBindingDivisor)(GLuint vaobj, GLuint bindingindex, GLuint divisor);
void (GLAPIENTRYP glGetVertexArrayiv)(GLuint vaobj, GLenum pname, GLint *param);
void (GLAPIENTRYP glGetVertexArrayIndexediv)(GLuint vaobj, GLuint index, GLenum pname, GLint *param);
void (GLAPIENTRYP glGetVertexArrayIndexed64iv)(GLuint vaobj, GLuint index, GLenum pname, GLint64 *param);
void (GLAPIENTRYP glCreateSamplers)(GLsizei n, GLuint *samplers);
void (GLAPIENTRYP glCreateProgramPipelines)(GLsizei n, GLuint *pipelines);
void (GLAPIENTRYP glCreateQueries)(GLenum target, GLsizei n, GLuint *ids);
void (GLAPIENTRYP glGetQueryBufferObjecti64v)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (GLAPIENTRYP glGetQueryBufferObjectiv)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (GLAPIENTRYP glGetQueryBufferObjectui64v)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (GLAPIENTRYP glGetQueryBufferObjectuiv)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
void (GLAPIENTRYP glMemoryBarrierByRegion)(GLbitfield barriers);
void (GLAPIENTRYP glGetTextureSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
void (GLAPIENTRYP glGetCompressedTextureSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void *pixels);
GLenum(GLAPIENTRYP glGetGraphicsResetStatus)(void);
void (GLAPIENTRYP glGetnCompressedTexImage)(GLenum target, GLint lod, GLsizei bufSize, void *pixels);
void (GLAPIENTRYP glGetnTexImage)(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
void (GLAPIENTRYP glGetnUniformdv)(GLuint program, GLint location, GLsizei bufSize, GLdouble *params);
void (GLAPIENTRYP glGetnUniformfv)(GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
void (GLAPIENTRYP glGetnUniformiv)(GLuint program, GLint location, GLsizei bufSize, GLint *params);
void (GLAPIENTRYP glGetnUniformuiv)(GLuint program, GLint location, GLsizei bufSize, GLuint *params);
void (GLAPIENTRYP glReadnPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
void (GLAPIENTRYP glTextureBarrier)(void);
GLuint64(GLAPIENTRYP glGetTextureHandleARB)(GLuint texture);
GLuint64(GLAPIENTRYP glGetTextureSamplerHandleARB)(GLuint texture, GLuint sampler);
void (GLAPIENTRYP glMakeTextureHandleResidentARB)(GLuint64 handle);
void (GLAPIENTRYP glMakeTextureHandleNonResidentARB)(GLuint64 handle);
GLuint64(GLAPIENTRYP glGetImageHandleARB)(GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum format);
void (GLAPIENTRYP glMakeImageHandleResidentARB)(GLuint64 handle, GLenum access);
void (GLAPIENTRYP glMakeImageHandleNonResidentARB)(GLuint64 handle);
void (GLAPIENTRYP glUniformHandleui64ARB)(GLint location, GLuint64 value);
void (GLAPIENTRYP glUniformHandleui64vARB)(GLint location, GLsizei count, const GLuint64 *value);
void (GLAPIENTRYP glProgramUniformHandleui64ARB)(GLuint program, GLint location, GLuint64 value);
void (GLAPIENTRYP glProgramUniformHandleui64vARB)(GLuint program, GLint location, GLsizei count, const GLuint64 *values);
GLboolean(GLAPIENTRYP glIsTextureHandleResidentARB)(GLuint64 handle);
GLboolean(GLAPIENTRYP glIsImageHandleResidentARB)(GLuint64 handle);
void (GLAPIENTRYP glVertexAttribL1ui64ARB)(GLuint index, GLuint64EXT x);
void (GLAPIENTRYP glVertexAttribL1ui64vARB)(GLuint index, const GLuint64EXT *v);
void (GLAPIENTRYP glGetVertexAttribLui64vARB)(GLuint index, GLenum pname, GLuint64EXT *params);
GLsync(GLAPIENTRYP glCreateSyncFromCLeventARB)(struct _cl_context *context, struct _cl_event *event, GLbitfield flags);
void (GLAPIENTRYP glDispatchComputeGroupSizeARB)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z, GLuint group_size_x, GLuint group_size_y, GLuint group_size_z);
void (GLAPIENTRYP glDebugMessageControlARB)(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
void (GLAPIENTRYP glDebugMessageInsertARB)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
void (GLAPIENTRYP glDebugMessageCallbackARB)(GLDEBUGPROCARB callback, const void *userParam);
GLuint(GLAPIENTRYP glGetDebugMessageLogARB)(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog);
void (GLAPIENTRYP glBlendEquationiARB)(GLuint buf, GLenum mode);
void (GLAPIENTRYP glBlendEquationSeparateiARB)(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
void (GLAPIENTRYP glBlendFunciARB)(GLuint buf, GLenum src, GLenum dst);
void (GLAPIENTRYP glBlendFuncSeparateiARB)(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void (GLAPIENTRYP glMultiDrawArraysIndirectCountARB)(GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
void (GLAPIENTRYP glMultiDrawElementsIndirectCountARB)(GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
GLenum(GLAPIENTRYP glGetGraphicsResetStatusARB)(void);
void (GLAPIENTRYP glGetnTexImageARB)(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *img);
void (GLAPIENTRYP glReadnPixelsARB)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
void (GLAPIENTRYP glGetnCompressedTexImageARB)(GLenum target, GLint lod, GLsizei bufSize, void *img);
void (GLAPIENTRYP glGetnUniformfvARB)(GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
void (GLAPIENTRYP glGetnUniformivARB)(GLuint program, GLint location, GLsizei bufSize, GLint *params);
void (GLAPIENTRYP glGetnUniformuivARB)(GLuint program, GLint location, GLsizei bufSize, GLuint *params);
void (GLAPIENTRYP glGetnUniformdvARB)(GLuint program, GLint location, GLsizei bufSize, GLdouble *params);
void (GLAPIENTRYP glMinSampleShadingARB)(GLfloat value);
void (GLAPIENTRYP glNamedStringARB)(GLenum type, GLint namelen, const GLchar *name, GLint stringlen, const GLchar *string);
void (GLAPIENTRYP glDeleteNamedStringARB)(GLint namelen, const GLchar *name);
void (GLAPIENTRYP glCompileShaderIncludeARB)(GLuint shader, GLsizei count, const GLchar *const*path, const GLint *length);
GLboolean(GLAPIENTRYP glIsNamedStringARB)(GLint namelen, const GLchar *name);
void (GLAPIENTRYP glGetNamedStringARB)(GLint namelen, const GLchar *name, GLsizei bufSize, GLint *stringlen, GLchar *string);
void (GLAPIENTRYP glGetNamedStringivARB)(GLint namelen, const GLchar *name, GLenum pname, GLint *params);
void (GLAPIENTRYP glBufferPageCommitmentARB)(GLenum target, GLintptr offset, GLsizeiptr size, GLboolean commit);
void (GLAPIENTRYP glNamedBufferPageCommitmentEXT)(GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit);
void (GLAPIENTRYP glNamedBufferPageCommitmentARB)(GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit);
void (GLAPIENTRYP glTexPageCommitmentARB)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLboolean commit);

#include <Windows.h>

template<class F>
void GetProcGL(F*& proc, const char* name)
{
    proc = (F*)wglGetProcAddress(name);
    if (!proc)
    {
        // Fall back to GetProcAddress to get GL 1 functions. wglGetProcAddress returns NULL on those.
        static HMODULE hOpenGL32 = LoadLibrary(TEXT("OpenGL32.dll"));
        proc = (F*)GetProcAddress(hOpenGL32, name);
    }
}

#define GET_PROC_GL(n) GetProcGL(n, #n)

void OpenGL_Init()
{
    GET_PROC_GL(glCullFace);
    GET_PROC_GL(glFrontFace);
    GET_PROC_GL(glHint);
    GET_PROC_GL(glLineWidth);
    GET_PROC_GL(glPointSize);
    GET_PROC_GL(glPolygonMode);
    GET_PROC_GL(glScissor);
    GET_PROC_GL(glTexParameterf);
    GET_PROC_GL(glTexParameterfv);
    GET_PROC_GL(glTexParameteri);
    GET_PROC_GL(glTexParameteriv);
    GET_PROC_GL(glTexImage1D);
    GET_PROC_GL(glTexImage2D);
    GET_PROC_GL(glDrawBuffer);
    GET_PROC_GL(glClear);
    GET_PROC_GL(glClearColor);
    GET_PROC_GL(glClearStencil);
    GET_PROC_GL(glClearDepth);
    GET_PROC_GL(glStencilMask);
    GET_PROC_GL(glColorMask);
    GET_PROC_GL(glDepthMask);
    GET_PROC_GL(glDisable);
    GET_PROC_GL(glEnable);
    GET_PROC_GL(glFinish);
    GET_PROC_GL(glFlush);
    GET_PROC_GL(glBlendFunc);
    GET_PROC_GL(glLogicOp);
    GET_PROC_GL(glStencilFunc);
    GET_PROC_GL(glStencilOp);
    GET_PROC_GL(glDepthFunc);
    GET_PROC_GL(glPixelStoref);
    GET_PROC_GL(glPixelStorei);
    GET_PROC_GL(glReadBuffer);
    GET_PROC_GL(glReadPixels);
    GET_PROC_GL(glGetBooleanv);
    GET_PROC_GL(glGetDoublev);
    GET_PROC_GL(glGetError);
    GET_PROC_GL(glGetFloatv);
    GET_PROC_GL(glGetIntegerv);
    GET_PROC_GL(glGetString);
    GET_PROC_GL(glGetTexImage);
    GET_PROC_GL(glGetTexParameterfv);
    GET_PROC_GL(glGetTexParameteriv);
    GET_PROC_GL(glGetTexLevelParameterfv);
    GET_PROC_GL(glGetTexLevelParameteriv);
    GET_PROC_GL(glIsEnabled);
    GET_PROC_GL(glDepthRange);
    GET_PROC_GL(glViewport);
    GET_PROC_GL(glDrawArrays);
    GET_PROC_GL(glDrawElements);
    GET_PROC_GL(glGetPointerv);
    GET_PROC_GL(glPolygonOffset);
    GET_PROC_GL(glCopyTexImage1D);
    GET_PROC_GL(glCopyTexImage2D);
    GET_PROC_GL(glCopyTexSubImage1D);
    GET_PROC_GL(glCopyTexSubImage2D);
    GET_PROC_GL(glTexSubImage1D);
    GET_PROC_GL(glTexSubImage2D);
    GET_PROC_GL(glBindTexture);
    GET_PROC_GL(glDeleteTextures);
    GET_PROC_GL(glGenTextures);
    GET_PROC_GL(glIsTexture);
    GET_PROC_GL(glDrawRangeElements);
    GET_PROC_GL(glTexImage3D);
    GET_PROC_GL(glTexSubImage3D);
    GET_PROC_GL(glCopyTexSubImage3D);
    GET_PROC_GL(glActiveTexture);
    GET_PROC_GL(glSampleCoverage);
    GET_PROC_GL(glCompressedTexImage3D);
    GET_PROC_GL(glCompressedTexImage2D);
    GET_PROC_GL(glCompressedTexImage1D);
    GET_PROC_GL(glCompressedTexSubImage3D);
    GET_PROC_GL(glCompressedTexSubImage2D);
    GET_PROC_GL(glCompressedTexSubImage1D);
    GET_PROC_GL(glGetCompressedTexImage);
    GET_PROC_GL(glBlendFuncSeparate);
    GET_PROC_GL(glMultiDrawArrays);
    GET_PROC_GL(glMultiDrawElements);
    GET_PROC_GL(glPointParameterf);
    GET_PROC_GL(glPointParameterfv);
    GET_PROC_GL(glPointParameteri);
    GET_PROC_GL(glPointParameteriv);
    GET_PROC_GL(glBlendColor);
    GET_PROC_GL(glBlendEquation);
    GET_PROC_GL(glGenQueries);
    GET_PROC_GL(glDeleteQueries);
    GET_PROC_GL(glIsQuery);
    GET_PROC_GL(glBeginQuery);
    GET_PROC_GL(glEndQuery);
    GET_PROC_GL(glGetQueryiv);
    GET_PROC_GL(glGetQueryObjectiv);
    GET_PROC_GL(glGetQueryObjectuiv);
    GET_PROC_GL(glBindBuffer);
    GET_PROC_GL(glDeleteBuffers);
    GET_PROC_GL(glGenBuffers);
    GET_PROC_GL(glIsBuffer);
    GET_PROC_GL(glBufferData);
    GET_PROC_GL(glBufferSubData);
    GET_PROC_GL(glGetBufferSubData);
    GET_PROC_GL(glMapBuffer);
    GET_PROC_GL(glUnmapBuffer);
    GET_PROC_GL(glGetBufferParameteriv);
    GET_PROC_GL(glGetBufferPointerv);
    GET_PROC_GL(glBlendEquationSeparate);
    GET_PROC_GL(glDrawBuffers);
    GET_PROC_GL(glStencilOpSeparate);
    GET_PROC_GL(glStencilFuncSeparate);
    GET_PROC_GL(glStencilMaskSeparate);
    GET_PROC_GL(glAttachShader);
    GET_PROC_GL(glBindAttribLocation);
    GET_PROC_GL(glCompileShader);
    GET_PROC_GL(glCreateProgram);
    GET_PROC_GL(glCreateShader);
    GET_PROC_GL(glDeleteProgram);
    GET_PROC_GL(glDeleteShader);
    GET_PROC_GL(glDetachShader);
    GET_PROC_GL(glDisableVertexAttribArray);
    GET_PROC_GL(glEnableVertexAttribArray);
    GET_PROC_GL(glGetActiveAttrib);
    GET_PROC_GL(glGetActiveUniform);
    GET_PROC_GL(glGetAttachedShaders);
    GET_PROC_GL(glGetAttribLocation);
    GET_PROC_GL(glGetProgramiv);
    GET_PROC_GL(glGetProgramInfoLog);
    GET_PROC_GL(glGetShaderiv);
    GET_PROC_GL(glGetShaderInfoLog);
    GET_PROC_GL(glGetShaderSource);
    GET_PROC_GL(glGetUniformLocation);
    GET_PROC_GL(glGetUniformfv);
    GET_PROC_GL(glGetUniformiv);
    GET_PROC_GL(glGetVertexAttribdv);
    GET_PROC_GL(glGetVertexAttribfv);
    GET_PROC_GL(glGetVertexAttribiv);
    GET_PROC_GL(glGetVertexAttribPointerv);
    GET_PROC_GL(glIsProgram);
    GET_PROC_GL(glIsShader);
    GET_PROC_GL(glLinkProgram);
    GET_PROC_GL(glShaderSource);
    GET_PROC_GL(glUseProgram);
    GET_PROC_GL(glUniform1f);
    GET_PROC_GL(glUniform2f);
    GET_PROC_GL(glUniform3f);
    GET_PROC_GL(glUniform4f);
    GET_PROC_GL(glUniform1i);
    GET_PROC_GL(glUniform2i);
    GET_PROC_GL(glUniform3i);
    GET_PROC_GL(glUniform4i);
    GET_PROC_GL(glUniform1fv);
    GET_PROC_GL(glUniform2fv);
    GET_PROC_GL(glUniform3fv);
    GET_PROC_GL(glUniform4fv);
    GET_PROC_GL(glUniform1iv);
    GET_PROC_GL(glUniform2iv);
    GET_PROC_GL(glUniform3iv);
    GET_PROC_GL(glUniform4iv);
    GET_PROC_GL(glUniformMatrix2fv);
    GET_PROC_GL(glUniformMatrix3fv);
    GET_PROC_GL(glUniformMatrix4fv);
    GET_PROC_GL(glValidateProgram);
    GET_PROC_GL(glVertexAttrib1d);
    GET_PROC_GL(glVertexAttrib1dv);
    GET_PROC_GL(glVertexAttrib1f);
    GET_PROC_GL(glVertexAttrib1fv);
    GET_PROC_GL(glVertexAttrib1s);
    GET_PROC_GL(glVertexAttrib1sv);
    GET_PROC_GL(glVertexAttrib2d);
    GET_PROC_GL(glVertexAttrib2dv);
    GET_PROC_GL(glVertexAttrib2f);
    GET_PROC_GL(glVertexAttrib2fv);
    GET_PROC_GL(glVertexAttrib2s);
    GET_PROC_GL(glVertexAttrib2sv);
    GET_PROC_GL(glVertexAttrib3d);
    GET_PROC_GL(glVertexAttrib3dv);
    GET_PROC_GL(glVertexAttrib3f);
    GET_PROC_GL(glVertexAttrib3fv);
    GET_PROC_GL(glVertexAttrib3s);
    GET_PROC_GL(glVertexAttrib3sv);
    GET_PROC_GL(glVertexAttrib4Nbv);
    GET_PROC_GL(glVertexAttrib4Niv);
    GET_PROC_GL(glVertexAttrib4Nsv);
    GET_PROC_GL(glVertexAttrib4Nub);
    GET_PROC_GL(glVertexAttrib4Nubv);
    GET_PROC_GL(glVertexAttrib4Nuiv);
    GET_PROC_GL(glVertexAttrib4Nusv);
    GET_PROC_GL(glVertexAttrib4bv);
    GET_PROC_GL(glVertexAttrib4d);
    GET_PROC_GL(glVertexAttrib4dv);
    GET_PROC_GL(glVertexAttrib4f);
    GET_PROC_GL(glVertexAttrib4fv);
    GET_PROC_GL(glVertexAttrib4iv);
    GET_PROC_GL(glVertexAttrib4s);
    GET_PROC_GL(glVertexAttrib4sv);
    GET_PROC_GL(glVertexAttrib4ubv);
    GET_PROC_GL(glVertexAttrib4uiv);
    GET_PROC_GL(glVertexAttrib4usv);
    GET_PROC_GL(glVertexAttribPointer);
    GET_PROC_GL(glUniformMatrix2x3fv);
    GET_PROC_GL(glUniformMatrix3x2fv);
    GET_PROC_GL(glUniformMatrix2x4fv);
    GET_PROC_GL(glUniformMatrix4x2fv);
    GET_PROC_GL(glUniformMatrix3x4fv);
    GET_PROC_GL(glUniformMatrix4x3fv);
    GET_PROC_GL(glColorMaski);
    GET_PROC_GL(glGetBooleani_v);
    GET_PROC_GL(glGetIntegeri_v);
    GET_PROC_GL(glEnablei);
    GET_PROC_GL(glDisablei);
    GET_PROC_GL(glIsEnabledi);
    GET_PROC_GL(glBeginTransformFeedback);
    GET_PROC_GL(glEndTransformFeedback);
    GET_PROC_GL(glBindBufferRange);
    GET_PROC_GL(glBindBufferBase);
    GET_PROC_GL(glTransformFeedbackVaryings);
    GET_PROC_GL(glGetTransformFeedbackVarying);
    GET_PROC_GL(glClampColor);
    GET_PROC_GL(glBeginConditionalRender);
    GET_PROC_GL(glEndConditionalRender);
    GET_PROC_GL(glVertexAttribIPointer);
    GET_PROC_GL(glGetVertexAttribIiv);
    GET_PROC_GL(glGetVertexAttribIuiv);
    GET_PROC_GL(glVertexAttribI1i);
    GET_PROC_GL(glVertexAttribI2i);
    GET_PROC_GL(glVertexAttribI3i);
    GET_PROC_GL(glVertexAttribI4i);
    GET_PROC_GL(glVertexAttribI1ui);
    GET_PROC_GL(glVertexAttribI2ui);
    GET_PROC_GL(glVertexAttribI3ui);
    GET_PROC_GL(glVertexAttribI4ui);
    GET_PROC_GL(glVertexAttribI1iv);
    GET_PROC_GL(glVertexAttribI2iv);
    GET_PROC_GL(glVertexAttribI3iv);
    GET_PROC_GL(glVertexAttribI4iv);
    GET_PROC_GL(glVertexAttribI1uiv);
    GET_PROC_GL(glVertexAttribI2uiv);
    GET_PROC_GL(glVertexAttribI3uiv);
    GET_PROC_GL(glVertexAttribI4uiv);
    GET_PROC_GL(glVertexAttribI4bv);
    GET_PROC_GL(glVertexAttribI4sv);
    GET_PROC_GL(glVertexAttribI4ubv);
    GET_PROC_GL(glVertexAttribI4usv);
    GET_PROC_GL(glGetUniformuiv);
    GET_PROC_GL(glBindFragDataLocation);
    GET_PROC_GL(glGetFragDataLocation);
    GET_PROC_GL(glUniform1ui);
    GET_PROC_GL(glUniform2ui);
    GET_PROC_GL(glUniform3ui);
    GET_PROC_GL(glUniform4ui);
    GET_PROC_GL(glUniform1uiv);
    GET_PROC_GL(glUniform2uiv);
    GET_PROC_GL(glUniform3uiv);
    GET_PROC_GL(glUniform4uiv);
    GET_PROC_GL(glTexParameterIiv);
    GET_PROC_GL(glTexParameterIuiv);
    GET_PROC_GL(glGetTexParameterIiv);
    GET_PROC_GL(glGetTexParameterIuiv);
    GET_PROC_GL(glClearBufferiv);
    GET_PROC_GL(glClearBufferuiv);
    GET_PROC_GL(glClearBufferfv);
    GET_PROC_GL(glClearBufferfi);
    GET_PROC_GL(glGetStringi);
    GET_PROC_GL(glIsRenderbuffer);
    GET_PROC_GL(glBindRenderbuffer);
    GET_PROC_GL(glDeleteRenderbuffers);
    GET_PROC_GL(glGenRenderbuffers);
    GET_PROC_GL(glRenderbufferStorage);
    GET_PROC_GL(glGetRenderbufferParameteriv);
    GET_PROC_GL(glIsFramebuffer);
    GET_PROC_GL(glBindFramebuffer);
    GET_PROC_GL(glDeleteFramebuffers);
    GET_PROC_GL(glGenFramebuffers);
    GET_PROC_GL(glCheckFramebufferStatus);
    GET_PROC_GL(glFramebufferTexture1D);
    GET_PROC_GL(glFramebufferTexture2D);
    GET_PROC_GL(glFramebufferTexture3D);
    GET_PROC_GL(glFramebufferRenderbuffer);
    GET_PROC_GL(glGetFramebufferAttachmentParameteriv);
    GET_PROC_GL(glGenerateMipmap);
    GET_PROC_GL(glBlitFramebuffer);
    GET_PROC_GL(glRenderbufferStorageMultisample);
    GET_PROC_GL(glFramebufferTextureLayer);
    GET_PROC_GL(glMapBufferRange);
    GET_PROC_GL(glFlushMappedBufferRange);
    GET_PROC_GL(glBindVertexArray);
    GET_PROC_GL(glDeleteVertexArrays);
    GET_PROC_GL(glGenVertexArrays);
    GET_PROC_GL(glIsVertexArray);
    GET_PROC_GL(glDrawArraysInstanced);
    GET_PROC_GL(glDrawElementsInstanced);
    GET_PROC_GL(glTexBuffer);
    GET_PROC_GL(glPrimitiveRestartIndex);
    GET_PROC_GL(glCopyBufferSubData);
    GET_PROC_GL(glGetUniformIndices);
    GET_PROC_GL(glGetActiveUniformsiv);
    GET_PROC_GL(glGetActiveUniformName);
    GET_PROC_GL(glGetUniformBlockIndex);
    GET_PROC_GL(glGetActiveUniformBlockiv);
    GET_PROC_GL(glGetActiveUniformBlockName);
    GET_PROC_GL(glUniformBlockBinding);
    GET_PROC_GL(glDrawElementsBaseVertex);
    GET_PROC_GL(glDrawRangeElementsBaseVertex);
    GET_PROC_GL(glDrawElementsInstancedBaseVertex);
    GET_PROC_GL(glMultiDrawElementsBaseVertex);
    GET_PROC_GL(glProvokingVertex);
    GET_PROC_GL(glFenceSync);
    GET_PROC_GL(glIsSync);
    GET_PROC_GL(glDeleteSync);
    GET_PROC_GL(glClientWaitSync);
    GET_PROC_GL(glWaitSync);
    GET_PROC_GL(glGetInteger64v);
    GET_PROC_GL(glGetSynciv);
    GET_PROC_GL(glGetInteger64i_v);
    GET_PROC_GL(glGetBufferParameteri64v);
    GET_PROC_GL(glFramebufferTexture);
    GET_PROC_GL(glTexImage2DMultisample);
    GET_PROC_GL(glTexImage3DMultisample);
    GET_PROC_GL(glGetMultisamplefv);
    GET_PROC_GL(glSampleMaski);
    GET_PROC_GL(glBindFragDataLocationIndexed);
    GET_PROC_GL(glGetFragDataIndex);
    GET_PROC_GL(glGenSamplers);
    GET_PROC_GL(glDeleteSamplers);
    GET_PROC_GL(glIsSampler);
    GET_PROC_GL(glBindSampler);
    GET_PROC_GL(glSamplerParameteri);
    GET_PROC_GL(glSamplerParameteriv);
    GET_PROC_GL(glSamplerParameterf);
    GET_PROC_GL(glSamplerParameterfv);
    GET_PROC_GL(glSamplerParameterIiv);
    GET_PROC_GL(glSamplerParameterIuiv);
    GET_PROC_GL(glGetSamplerParameteriv);
    GET_PROC_GL(glGetSamplerParameterIiv);
    GET_PROC_GL(glGetSamplerParameterfv);
    GET_PROC_GL(glGetSamplerParameterIuiv);
    GET_PROC_GL(glQueryCounter);
    GET_PROC_GL(glGetQueryObjecti64v);
    GET_PROC_GL(glGetQueryObjectui64v);
    GET_PROC_GL(glVertexAttribDivisor);
    GET_PROC_GL(glVertexAttribP1ui);
    GET_PROC_GL(glVertexAttribP1uiv);
    GET_PROC_GL(glVertexAttribP2ui);
    GET_PROC_GL(glVertexAttribP2uiv);
    GET_PROC_GL(glVertexAttribP3ui);
    GET_PROC_GL(glVertexAttribP3uiv);
    GET_PROC_GL(glVertexAttribP4ui);
    GET_PROC_GL(glVertexAttribP4uiv);
    GET_PROC_GL(glMinSampleShading);
    GET_PROC_GL(glBlendEquationi);
    GET_PROC_GL(glBlendEquationSeparatei);
    GET_PROC_GL(glBlendFunci);
    GET_PROC_GL(glBlendFuncSeparatei);
    GET_PROC_GL(glDrawArraysIndirect);
    GET_PROC_GL(glDrawElementsIndirect);
    GET_PROC_GL(glUniform1d);
    GET_PROC_GL(glUniform2d);
    GET_PROC_GL(glUniform3d);
    GET_PROC_GL(glUniform4d);
    GET_PROC_GL(glUniform1dv);
    GET_PROC_GL(glUniform2dv);
    GET_PROC_GL(glUniform3dv);
    GET_PROC_GL(glUniform4dv);
    GET_PROC_GL(glUniformMatrix2dv);
    GET_PROC_GL(glUniformMatrix3dv);
    GET_PROC_GL(glUniformMatrix4dv);
    GET_PROC_GL(glUniformMatrix2x3dv);
    GET_PROC_GL(glUniformMatrix2x4dv);
    GET_PROC_GL(glUniformMatrix3x2dv);
    GET_PROC_GL(glUniformMatrix3x4dv);
    GET_PROC_GL(glUniformMatrix4x2dv);
    GET_PROC_GL(glUniformMatrix4x3dv);
    GET_PROC_GL(glGetUniformdv);
    GET_PROC_GL(glGetSubroutineUniformLocation);
    GET_PROC_GL(glGetSubroutineIndex);
    GET_PROC_GL(glGetActiveSubroutineUniformiv);
    GET_PROC_GL(glGetActiveSubroutineUniformName);
    GET_PROC_GL(glGetActiveSubroutineName);
    GET_PROC_GL(glUniformSubroutinesuiv);
    GET_PROC_GL(glGetUniformSubroutineuiv);
    GET_PROC_GL(glGetProgramStageiv);
    GET_PROC_GL(glPatchParameteri);
    GET_PROC_GL(glPatchParameterfv);
    GET_PROC_GL(glBindTransformFeedback);
    GET_PROC_GL(glDeleteTransformFeedbacks);
    GET_PROC_GL(glGenTransformFeedbacks);
    GET_PROC_GL(glIsTransformFeedback);
    GET_PROC_GL(glPauseTransformFeedback);
    GET_PROC_GL(glResumeTransformFeedback);
    GET_PROC_GL(glDrawTransformFeedback);
    GET_PROC_GL(glDrawTransformFeedbackStream);
    GET_PROC_GL(glBeginQueryIndexed);
    GET_PROC_GL(glEndQueryIndexed);
    GET_PROC_GL(glGetQueryIndexediv);
    GET_PROC_GL(glReleaseShaderCompiler);
    GET_PROC_GL(glShaderBinary);
    GET_PROC_GL(glGetShaderPrecisionFormat);
    GET_PROC_GL(glDepthRangef);
    GET_PROC_GL(glClearDepthf);
    GET_PROC_GL(glGetProgramBinary);
    GET_PROC_GL(glProgramBinary);
    GET_PROC_GL(glProgramParameteri);
    GET_PROC_GL(glUseProgramStages);
    GET_PROC_GL(glActiveShaderProgram);
    GET_PROC_GL(glCreateShaderProgramv);
    GET_PROC_GL(glBindProgramPipeline);
    GET_PROC_GL(glDeleteProgramPipelines);
    GET_PROC_GL(glGenProgramPipelines);
    GET_PROC_GL(glIsProgramPipeline);
    GET_PROC_GL(glGetProgramPipelineiv);
    GET_PROC_GL(glProgramUniform1i);
    GET_PROC_GL(glProgramUniform1iv);
    GET_PROC_GL(glProgramUniform1f);
    GET_PROC_GL(glProgramUniform1fv);
    GET_PROC_GL(glProgramUniform1d);
    GET_PROC_GL(glProgramUniform1dv);
    GET_PROC_GL(glProgramUniform1ui);
    GET_PROC_GL(glProgramUniform1uiv);
    GET_PROC_GL(glProgramUniform2i);
    GET_PROC_GL(glProgramUniform2iv);
    GET_PROC_GL(glProgramUniform2f);
    GET_PROC_GL(glProgramUniform2fv);
    GET_PROC_GL(glProgramUniform2d);
    GET_PROC_GL(glProgramUniform2dv);
    GET_PROC_GL(glProgramUniform2ui);
    GET_PROC_GL(glProgramUniform2uiv);
    GET_PROC_GL(glProgramUniform3i);
    GET_PROC_GL(glProgramUniform3iv);
    GET_PROC_GL(glProgramUniform3f);
    GET_PROC_GL(glProgramUniform3fv);
    GET_PROC_GL(glProgramUniform3d);
    GET_PROC_GL(glProgramUniform3dv);
    GET_PROC_GL(glProgramUniform3ui);
    GET_PROC_GL(glProgramUniform3uiv);
    GET_PROC_GL(glProgramUniform4i);
    GET_PROC_GL(glProgramUniform4iv);
    GET_PROC_GL(glProgramUniform4f);
    GET_PROC_GL(glProgramUniform4fv);
    GET_PROC_GL(glProgramUniform4d);
    GET_PROC_GL(glProgramUniform4dv);
    GET_PROC_GL(glProgramUniform4ui);
    GET_PROC_GL(glProgramUniform4uiv);
    GET_PROC_GL(glProgramUniformMatrix2fv);
    GET_PROC_GL(glProgramUniformMatrix3fv);
    GET_PROC_GL(glProgramUniformMatrix4fv);
    GET_PROC_GL(glProgramUniformMatrix2dv);
    GET_PROC_GL(glProgramUniformMatrix3dv);
    GET_PROC_GL(glProgramUniformMatrix4dv);
    GET_PROC_GL(glProgramUniformMatrix2x3fv);
    GET_PROC_GL(glProgramUniformMatrix3x2fv);
    GET_PROC_GL(glProgramUniformMatrix2x4fv);
    GET_PROC_GL(glProgramUniformMatrix4x2fv);
    GET_PROC_GL(glProgramUniformMatrix3x4fv);
    GET_PROC_GL(glProgramUniformMatrix4x3fv);
    GET_PROC_GL(glProgramUniformMatrix2x3dv);
    GET_PROC_GL(glProgramUniformMatrix3x2dv);
    GET_PROC_GL(glProgramUniformMatrix2x4dv);
    GET_PROC_GL(glProgramUniformMatrix4x2dv);
    GET_PROC_GL(glProgramUniformMatrix3x4dv);
    GET_PROC_GL(glProgramUniformMatrix4x3dv);
    GET_PROC_GL(glValidateProgramPipeline);
    GET_PROC_GL(glGetProgramPipelineInfoLog);
    GET_PROC_GL(glVertexAttribL1d);
    GET_PROC_GL(glVertexAttribL2d);
    GET_PROC_GL(glVertexAttribL3d);
    GET_PROC_GL(glVertexAttribL4d);
    GET_PROC_GL(glVertexAttribL1dv);
    GET_PROC_GL(glVertexAttribL2dv);
    GET_PROC_GL(glVertexAttribL3dv);
    GET_PROC_GL(glVertexAttribL4dv);
    GET_PROC_GL(glVertexAttribLPointer);
    GET_PROC_GL(glGetVertexAttribLdv);
    GET_PROC_GL(glViewportArrayv);
    GET_PROC_GL(glViewportIndexedf);
    GET_PROC_GL(glViewportIndexedfv);
    GET_PROC_GL(glScissorArrayv);
    GET_PROC_GL(glScissorIndexed);
    GET_PROC_GL(glScissorIndexedv);
    GET_PROC_GL(glDepthRangeArrayv);
    GET_PROC_GL(glDepthRangeIndexed);
    GET_PROC_GL(glGetFloati_v);
    GET_PROC_GL(glGetDoublei_v);
    GET_PROC_GL(glDrawArraysInstancedBaseInstance);
    GET_PROC_GL(glDrawElementsInstancedBaseInstance);
    GET_PROC_GL(glDrawElementsInstancedBaseVertexBaseInstance);
    GET_PROC_GL(glGetInternalformativ);
    GET_PROC_GL(glGetActiveAtomicCounterBufferiv);
    GET_PROC_GL(glBindImageTexture);
    GET_PROC_GL(glMemoryBarrier);
    GET_PROC_GL(glTexStorage1D);
    GET_PROC_GL(glTexStorage2D);
    GET_PROC_GL(glTexStorage3D);
    GET_PROC_GL(glDrawTransformFeedbackInstanced);
    GET_PROC_GL(glDrawTransformFeedbackStreamInstanced);
    GET_PROC_GL(glClearBufferData);
    GET_PROC_GL(glClearBufferSubData);
    GET_PROC_GL(glDispatchCompute);
    GET_PROC_GL(glDispatchComputeIndirect);
    GET_PROC_GL(glCopyImageSubData);
    GET_PROC_GL(glFramebufferParameteri);
    GET_PROC_GL(glGetFramebufferParameteriv);
    GET_PROC_GL(glGetInternalformati64v);
    GET_PROC_GL(glInvalidateTexSubImage);
    GET_PROC_GL(glInvalidateTexImage);
    GET_PROC_GL(glInvalidateBufferSubData);
    GET_PROC_GL(glInvalidateBufferData);
    GET_PROC_GL(glInvalidateFramebuffer);
    GET_PROC_GL(glInvalidateSubFramebuffer);
    GET_PROC_GL(glMultiDrawArraysIndirect);
    GET_PROC_GL(glMultiDrawElementsIndirect);
    GET_PROC_GL(glGetProgramInterfaceiv);
    GET_PROC_GL(glGetProgramResourceIndex);
    GET_PROC_GL(glGetProgramResourceName);
    GET_PROC_GL(glGetProgramResourceiv);
    GET_PROC_GL(glGetProgramResourceLocation);
    GET_PROC_GL(glGetProgramResourceLocationIndex);
    GET_PROC_GL(glShaderStorageBlockBinding);
    GET_PROC_GL(glTexBufferRange);
    GET_PROC_GL(glTexStorage2DMultisample);
    GET_PROC_GL(glTexStorage3DMultisample);
    GET_PROC_GL(glTextureView);
    GET_PROC_GL(glBindVertexBuffer);
    GET_PROC_GL(glVertexAttribFormat);
    GET_PROC_GL(glVertexAttribIFormat);
    GET_PROC_GL(glVertexAttribLFormat);
    GET_PROC_GL(glVertexAttribBinding);
    GET_PROC_GL(glVertexBindingDivisor);
    GET_PROC_GL(glDebugMessageControl);
    GET_PROC_GL(glDebugMessageInsert);
    GET_PROC_GL(glDebugMessageCallback);
    GET_PROC_GL(glGetDebugMessageLog);
    GET_PROC_GL(glPushDebugGroup);
    GET_PROC_GL(glPopDebugGroup);
    GET_PROC_GL(glObjectLabel);
    GET_PROC_GL(glGetObjectLabel);
    GET_PROC_GL(glObjectPtrLabel);
    GET_PROC_GL(glGetObjectPtrLabel);
    GET_PROC_GL(glBufferStorage);
    GET_PROC_GL(glClearTexImage);
    GET_PROC_GL(glClearTexSubImage);
    GET_PROC_GL(glBindBuffersBase);
    GET_PROC_GL(glBindBuffersRange);
    GET_PROC_GL(glBindTextures);
    GET_PROC_GL(glBindSamplers);
    GET_PROC_GL(glBindImageTextures);
    GET_PROC_GL(glBindVertexBuffers);
    GET_PROC_GL(glClipControl);
    GET_PROC_GL(glCreateTransformFeedbacks);
    GET_PROC_GL(glTransformFeedbackBufferBase);
    GET_PROC_GL(glTransformFeedbackBufferRange);
    GET_PROC_GL(glGetTransformFeedbackiv);
    GET_PROC_GL(glGetTransformFeedbacki_v);
    GET_PROC_GL(glGetTransformFeedbacki64_v);
    GET_PROC_GL(glCreateBuffers);
    GET_PROC_GL(glNamedBufferStorage);
    GET_PROC_GL(glNamedBufferData);
    GET_PROC_GL(glNamedBufferSubData);
    GET_PROC_GL(glCopyNamedBufferSubData);
    GET_PROC_GL(glClearNamedBufferData);
    GET_PROC_GL(glClearNamedBufferSubData);
    GET_PROC_GL(glMapNamedBuffer);
    GET_PROC_GL(glMapNamedBufferRange);
    GET_PROC_GL(glUnmapNamedBuffer);
    GET_PROC_GL(glFlushMappedNamedBufferRange);
    GET_PROC_GL(glGetNamedBufferParameteriv);
    GET_PROC_GL(glGetNamedBufferParameteri64v);
    GET_PROC_GL(glGetNamedBufferPointerv);
    GET_PROC_GL(glGetNamedBufferSubData);
    GET_PROC_GL(glCreateFramebuffers);
    GET_PROC_GL(glNamedFramebufferRenderbuffer);
    GET_PROC_GL(glNamedFramebufferParameteri);
    GET_PROC_GL(glNamedFramebufferTexture);
    GET_PROC_GL(glNamedFramebufferTextureLayer);
    GET_PROC_GL(glNamedFramebufferDrawBuffer);
    GET_PROC_GL(glNamedFramebufferDrawBuffers);
    GET_PROC_GL(glNamedFramebufferReadBuffer);
    GET_PROC_GL(glInvalidateNamedFramebufferData);
    GET_PROC_GL(glInvalidateNamedFramebufferSubData);
    GET_PROC_GL(glClearNamedFramebufferiv);
    GET_PROC_GL(glClearNamedFramebufferuiv);
    GET_PROC_GL(glClearNamedFramebufferfv);
    GET_PROC_GL(glClearNamedFramebufferfi);
    GET_PROC_GL(glBlitNamedFramebuffer);
    GET_PROC_GL(glCheckNamedFramebufferStatus);
    GET_PROC_GL(glGetNamedFramebufferParameteriv);
    GET_PROC_GL(glGetNamedFramebufferAttachmentParameteriv);
    GET_PROC_GL(glCreateRenderbuffers);
    GET_PROC_GL(glNamedRenderbufferStorage);
    GET_PROC_GL(glNamedRenderbufferStorageMultisample);
    GET_PROC_GL(glGetNamedRenderbufferParameteriv);
    GET_PROC_GL(glCreateTextures);
    GET_PROC_GL(glTextureBuffer);
    GET_PROC_GL(glTextureBufferRange);
    GET_PROC_GL(glTextureStorage1D);
    GET_PROC_GL(glTextureStorage2D);
    GET_PROC_GL(glTextureStorage3D);
    GET_PROC_GL(glTextureStorage2DMultisample);
    GET_PROC_GL(glTextureStorage3DMultisample);
    GET_PROC_GL(glTextureSubImage1D);
    GET_PROC_GL(glTextureSubImage2D);
    GET_PROC_GL(glTextureSubImage3D);
    GET_PROC_GL(glCompressedTextureSubImage1D);
    GET_PROC_GL(glCompressedTextureSubImage2D);
    GET_PROC_GL(glCompressedTextureSubImage3D);
    GET_PROC_GL(glCopyTextureSubImage1D);
    GET_PROC_GL(glCopyTextureSubImage2D);
    GET_PROC_GL(glCopyTextureSubImage3D);
    GET_PROC_GL(glTextureParameterf);
    GET_PROC_GL(glTextureParameterfv);
    GET_PROC_GL(glTextureParameteri);
    GET_PROC_GL(glTextureParameterIiv);
    GET_PROC_GL(glTextureParameterIuiv);
    GET_PROC_GL(glTextureParameteriv);
    GET_PROC_GL(glGenerateTextureMipmap);
    GET_PROC_GL(glBindTextureUnit);
    GET_PROC_GL(glGetTextureImage);
    GET_PROC_GL(glGetCompressedTextureImage);
    GET_PROC_GL(glGetTextureLevelParameterfv);
    GET_PROC_GL(glGetTextureLevelParameteriv);
    GET_PROC_GL(glGetTextureParameterfv);
    GET_PROC_GL(glGetTextureParameterIiv);
    GET_PROC_GL(glGetTextureParameterIuiv);
    GET_PROC_GL(glGetTextureParameteriv);
    GET_PROC_GL(glCreateVertexArrays);
    GET_PROC_GL(glDisableVertexArrayAttrib);
    GET_PROC_GL(glEnableVertexArrayAttrib);
    GET_PROC_GL(glVertexArrayElementBuffer);
    GET_PROC_GL(glVertexArrayVertexBuffer);
    GET_PROC_GL(glVertexArrayVertexBuffers);
    GET_PROC_GL(glVertexArrayAttribBinding);
    GET_PROC_GL(glVertexArrayAttribFormat);
    GET_PROC_GL(glVertexArrayAttribIFormat);
    GET_PROC_GL(glVertexArrayAttribLFormat);
    GET_PROC_GL(glVertexArrayBindingDivisor);
    GET_PROC_GL(glGetVertexArrayiv);
    GET_PROC_GL(glGetVertexArrayIndexediv);
    GET_PROC_GL(glGetVertexArrayIndexed64iv);
    GET_PROC_GL(glCreateSamplers);
    GET_PROC_GL(glCreateProgramPipelines);
    GET_PROC_GL(glCreateQueries);
    GET_PROC_GL(glGetQueryBufferObjecti64v);
    GET_PROC_GL(glGetQueryBufferObjectiv);
    GET_PROC_GL(glGetQueryBufferObjectui64v);
    GET_PROC_GL(glGetQueryBufferObjectuiv);
    GET_PROC_GL(glMemoryBarrierByRegion);
    GET_PROC_GL(glGetTextureSubImage);
    GET_PROC_GL(glGetCompressedTextureSubImage);
    GET_PROC_GL(glGetGraphicsResetStatus);
    GET_PROC_GL(glGetnCompressedTexImage);
    GET_PROC_GL(glGetnTexImage);
    GET_PROC_GL(glGetnUniformdv);
    GET_PROC_GL(glGetnUniformfv);
    GET_PROC_GL(glGetnUniformiv);
    GET_PROC_GL(glGetnUniformuiv);
    GET_PROC_GL(glReadnPixels);
    GET_PROC_GL(glTextureBarrier);
    GET_PROC_GL(glGetTextureHandleARB);
    GET_PROC_GL(glGetTextureSamplerHandleARB);
    GET_PROC_GL(glMakeTextureHandleResidentARB);
    GET_PROC_GL(glMakeTextureHandleNonResidentARB);
    GET_PROC_GL(glGetImageHandleARB);
    GET_PROC_GL(glMakeImageHandleResidentARB);
    GET_PROC_GL(glMakeImageHandleNonResidentARB);
    GET_PROC_GL(glUniformHandleui64ARB);
    GET_PROC_GL(glUniformHandleui64vARB);
    GET_PROC_GL(glProgramUniformHandleui64ARB);
    GET_PROC_GL(glProgramUniformHandleui64vARB);
    GET_PROC_GL(glIsTextureHandleResidentARB);
    GET_PROC_GL(glIsImageHandleResidentARB);
    GET_PROC_GL(glVertexAttribL1ui64ARB);
    GET_PROC_GL(glVertexAttribL1ui64vARB);
    GET_PROC_GL(glGetVertexAttribLui64vARB);
    GET_PROC_GL(glCreateSyncFromCLeventARB);
    GET_PROC_GL(glDispatchComputeGroupSizeARB);
    GET_PROC_GL(glDebugMessageControlARB);
    GET_PROC_GL(glDebugMessageInsertARB);
    GET_PROC_GL(glDebugMessageCallbackARB);
    GET_PROC_GL(glGetDebugMessageLogARB);
    GET_PROC_GL(glBlendEquationiARB);
    GET_PROC_GL(glBlendEquationSeparateiARB);
    GET_PROC_GL(glBlendFunciARB);
    GET_PROC_GL(glBlendFuncSeparateiARB);
    GET_PROC_GL(glMultiDrawArraysIndirectCountARB);
    GET_PROC_GL(glMultiDrawElementsIndirectCountARB);
    GET_PROC_GL(glGetGraphicsResetStatusARB);
    GET_PROC_GL(glGetnTexImageARB);
    GET_PROC_GL(glReadnPixelsARB);
    GET_PROC_GL(glGetnCompressedTexImageARB);
    GET_PROC_GL(glGetnUniformfvARB);
    GET_PROC_GL(glGetnUniformivARB);
    GET_PROC_GL(glGetnUniformuivARB);
    GET_PROC_GL(glGetnUniformdvARB);
    GET_PROC_GL(glMinSampleShadingARB);
    GET_PROC_GL(glNamedStringARB);
    GET_PROC_GL(glDeleteNamedStringARB);
    GET_PROC_GL(glCompileShaderIncludeARB);
    GET_PROC_GL(glIsNamedStringARB);
    GET_PROC_GL(glGetNamedStringARB);
    GET_PROC_GL(glGetNamedStringivARB);
    GET_PROC_GL(glBufferPageCommitmentARB);
    GET_PROC_GL(glNamedBufferPageCommitmentEXT);
    GET_PROC_GL(glNamedBufferPageCommitmentARB);
    GET_PROC_GL(glTexPageCommitmentARB);
}
